### ISSUE TITLE
Disable Squadron Notifications

### ISSUE THREAD

**Issue by brunocalado** [trioderegion/squadron#18]
Hi! Great module!

Can you add an option to disable squadron notifications?

![image](https://user-images.githubusercontent.com/4999783/180653336-ac02cdf7-40d8-4fb6-a74b-7f4c811e4b60.png)

tks

**Comment by trioderegion** [comment]
Hi, can you explain a little bit more about what's going on here? You can disable wall collision checks in squadron's options to dodge the check entirely. I feel like feedback when a token cannot continue following a leader is important, but I could be wrong.

**Comment by brunocalado** [comment]
> Hi, can you explain a little bit more about what's going on here? You can disable wall collision checks in squadron's options to dodge the check entirely. I feel like feedback when a token cannot continue following a leader is important, but I could be wrong.

Feedback is important. But, FVTT+modules are giving A LOT of feedback. Allow the user to disable the feedback would be nice.

It's just to don't show the blue message everytime you colide or something else.
